name: CI

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20.11.1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: corepack pnpm install

      - name: Lint
        run: corepack pnpm lint

      - name: Typecheck
        run: corepack pnpm typecheck

      - name: Test
        run: corepack pnpm test

      - name: Build
        run: corepack pnpm build
